sequenceDiagram
  participant browser
  participant server

  Note right of browser: user submits the form with a note
  browser->server: HTTP POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa

  Note middle of browser: the browser's JavaScript code adds the new note to the end of the note list and sends it to the server
